const countryOptions = [
    { value:  'World', flag: '', text: 'עולמי' },
    {  value: 'USA', flag: 'us', text: 'ארה"ב' },
    {  value: 'India', flag: 'in', text: 'הודו' },
    {  value: 'Algeria', flag: 'dz', text: "אלג'יריה" },
    {  value: 'Brazil', flag: 'br', text: 'ברזיל' },
    {  value: 'Russia', flag: 'ru', text: 'רוסיה' },
    {  value: 'France', flag: 'fr', text: 'צרפת' },
    {  value: 'Italy', flag: 'it', text: 'איטליה' },
    {  value: 'Israel', flag: 'il', text: 'ישראל' },
    {  value: 'Argentina', flag: 'ar', text: 'ארגנטינה' },
    {  value: 'Colombia', flag: 'co', text: 'קולומביה' },
    {  value: 'Mexico', flag: 'mx', text: 'מקסיקו' },
    {  value: 'Germany', flag: 'de', text: 'גרמניה' },
    {  value: 'Poland', flag: 'pl', text: 'פולין' },
    {  value: 'Peru', flag: 'pe', text: 'פרו' },
    {  value: 'Iran', flag: 'ir', text: 'אירן' },
    {  value: 'South Africa', flag: 'za', text: 'דרום אפריקה' },
    {  value: 'Ukraine', flag: 'ua', text: 'אוקראינה' },
    {  value: 'Belgium', flag: 'be', text: 'בלגיה' },
    {  value: 'Chile', flag: 'cl', text: "צ'ילה" },
    {  value: 'Iraq', flag: 'iq', text: 'עירק' },
    {  value: 'Indonesia', flag: 'id', text: 'אינדונזיה' },
    {  value: 'Czechia', flag: 'cz', text: "צ'כיה" },
    
    
    { value:  'Turkey', flag: 'tr', text: 'טורקיה' },
    {  value: 'Netherlands', flag: 'nl', text: 'הולנד' },
    {  value: 'Bangladesh', flag: 'bd', text: 'בנגלדש' },
    {  value: 'Romania', flag: 'ro', text: "רומניה" },
    {  value: 'UK', flag: 'gb', text: 'בריטניה' },
    {  value: 'Philippines', flag: 'ph', text: 'פיליפינים' },
    {  value: 'Pakistan', flag: 'pk', text: 'פקיסטן' },
    {  value: 'Saudi Arabia', flag: 'sa', text: 'ערב הסעודית' },
    {  value: 'Canada', flag: 'ca', text: 'קנדה' },
    {  value: 'Morocco', flag: 'ma', text: 'מרוקו' },
    {  value: 'Switzerland', flag: 'ch', text: 'שוויץ' },
    {  value: 'Portugal', flag: 'pt', text: 'פורטוגל' },
    {  value: 'Austria', flag: 'au', text: 'אוסטרליה' },
    {  value: 'Sweden', flag: 'se', text: 'שוודיה' },
    {  value: 'Nepal', flag: 'np', text: 'נאפל' },
    {  value: 'Jordan', flag: 'jo', text: 'ירדן' },
    {  value: 'Hungary', flag: 'hu', text: 'הונגריה' },
    {  value: 'Ecuador', flag: 'ec', text: 'אקוודור' },
    {  value: 'UAE', flag: 'ae', text: 'איחוד האמיריות' },
    {  value: 'Panama', flag: 'pa', text: 'פנמה' },
    {  value: 'Serbia', flag: 'rs', text: 'סרביה' },
    {  value: 'Bolivia', flag: 'bo', text: 'בוליביה' },
    {  value: 'Kuwait', flag: 'kw', text: "כווית" },
    {  value: 'Dominican Republic', flag: 'do', text: 'הרפובליקה הדומיניקנית' },
    {  value: 'Qatar', flag: 'qa', text: 'קטאר' },
    {  value: 'Japan', flag: 'jp', text: "יפן" },


    { value:  'Bulgaria', flag: 'bg', text: 'בולגריה' },
    {  value: 'Costa Rica', flag: 'cr', text: 'קוסטה ריקה' },
    {  value: 'Armenia', flag: 'am', text: 'ארמניה' },
    {  value: 'Belarus', flag: 'by', text: "בלרוס" },
    {  value: 'Kazakhstan', flag: 'kz', text: 'קזחסטן' },
    {  value: 'Georgia', flag: 'ge', text: "גאורגיה" },
    {  value: 'Oman', flag: 'om', text: 'עומאן' },
    {  value: 'Lebanon', flag: 'lb', text: 'לבנון' },
    {  value: 'Guatemala', flag: 'gt', text: 'גוואטמלה' },
    {  value: 'Croatia', flag: 'hr', text: 'קרואטיה' },
    {  value: 'Egypt', flag: 'eg', text: 'מצרים' },
    {  value: 'Ethiopia', flag: 'et', text: 'אתיופיה' },
    {  value: 'Honduras', flag: 'hn', text: 'הונדורס' },
    {  value: 'Azerbaijan', flag: 'az', text: 'אזרביגאן' },
    {  value: 'Slovakia', flag: 'sk', text: 'סלובקיה' },
    {  value: 'Moldova', flag: 'md', text: 'מלדובה' },
    {  value: 'Venezuela', flag: 've', text: 'ונצואלה' },
    {  value: 'Greece', flag: 'gr', text: 'יון' },
    {  value: 'Tunisia', flag: 'tn', text: 'תוניסיה' },
    {  value: 'Bahrain', flag: 'bh', text: 'בחרין' },
    {  value: 'Bosnia and Herzegovina', flag: 'ba', text: "בוסניה והרצגובינה" },
    {  value: 'Libya', flag: 'ly', text: 'לוב' },
    {  value: 'Kenya', flag: 'ke', text: 'קניה' },
    {  value: 'Paraguay', flag: 'py', text: "פרגוואי" },
    {  value: 'China', flag: 'cn', text: 'סין' },
    {  value: 'Thailand', flag: 'th', text: 'תאילנד' },


    {  value: 'Denmark', flag: 'dk', text: 'דנמרק' },
    {  value: 'Uzbekistan', flag: 'uz', text: 'אוזבקיסטן' },
    {  value: 'Kyrgyzstan', flag: 'kg', text: "קירגיזסטן" },
    {  value: 'Ireland', flag: 'ie', text: 'אירלנד' },
    {  value: 'Slovenia', flag: 'si', text: 'סלובניה' },
    {  value: 'Nigeria', flag: 'ng', text: 'ניגריה' },
    {  value: 'Malaysia', flag: 'my', text: 'מלזיה' },
    {  value: 'Singapore', flag: 'sg', text: 'סינגפור' },
    {  value: 'Lithuania', flag: 'lt', text: 'ליטא' },
    {  value: 'Ghana', flag: 'gh', text: 'גאנה' },
    {  value: 'Afghanistan', flag: 'af', text: 'אפגניסטן' },
    {  value: 'El Salvador', flag: 'sv', text: 'אל סלבדור' },
    {  value: 'Albania', flag: 'al', text: 'אלבניה' },
    {  value: 'Norway' , flag: 'no', text: 'נורווגיה' },
    {  value: 'S. Korea', flag: 'kr', text: 'דרום קוריאה' },
    {  value: 'Luxembourg', flag: 'lu', text: 'לוקסמבורג' },
    {  value: 'Australia', flag: 'au', text: 'אוסטרליה' },
    {  value: 'Cameroon', flag: 'cm', text: 'קמרון' },
    {  value: 'Finland', flag: 'fi', text: 'פינלנד' },
    {  value: 'Sri Lanka', flag: 'lk', text: "סרי לנקה" },
    {  value: 'Ivory Coast', flag: 'ci', text: 'חוף השנהב' },
    {  value: 'Uganda', flag: 'ug', text: "אוגנדה" },
  ]



  export default countryOptions;

